language: cpp
dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data

compiler:
    - clang
    - gcc

script:
    - ./tools/test_all.py
